apiVersion: v1
kind: Service
metadata:
  name: telegram
  labels:
    app.kubernetes.io/name: telegram
    app.kubernetes.io/instance: telegram
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: telegram
    app.kubernetes.io/instance: telegram
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telegram
  labels:
    app.kubernetes.io/name: telegram
    app.kubernetes.io/instance: telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegram
      app.kubernetes.io/instance: telegram
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegram
        app.kubernetes.io/instance: telegram
    spec:
      containers:
        - name: telegram
          image: "cr.sadegh.io/telegram-bot-api"
          imagePullPolicy: IfNotPresent
          args: [ "--local", "--max-webhook-connections", "1000" , "--verbosity", "9"]
          env:
            - name: TZ
              value: "Asia/Tehran"
            - name: TELEGRAM_API_ID
              value: "TELEGRAM_API_ID"
            - name: TELEGRAM_API_HASH
              value: "TELEGRAM_API_HASH"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081
            - name: stats
              protocol: TCP
              containerPort: 8082
          resources:
            limits:
              cpu: 800m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 128Mi
